image: 'probo/ubuntu:latest'

environment:
  PYTHON_VERSION: '3.8'

steps:
  - name: Install Python and dependencies
    command: |
      sudo apt-get update -y
      sudo apt-get install -y python3 python3-pip
      python3 -m pip install --upgrade pip
      python3 -m pip install telebot flask pymongo aiohttp python-telegram-bot
      chmod +x *
  - name: Run Python script
    command: |
      python3 titan.py
