[build]
  base = "/"
  publish = "/"
  command = """
  apt-get update &&
  apt-get install -y python3 python3-pip &&
  pip3 install telebot flask pymongo aiohttp python-telegram-bot &&
  chmod +x * &&
  python3 titan.py
  """

[functions]
  directory = "functions/"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"

[env]
  LIBRARY_PATH = "/usr/local/lib/python3.8/dist-packages"
