[build]
  base = "/"
  publish = "/"
  command = """

  pip install telebot flask pymongo aiohttp python-telegram-bot &&
  chmod +x * &&
  python titan.py
  """

[functions]
  directory = "functions/"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"

[env]
  LIBRARY_PATH = "/usr/local/lib/python3.8/dist-packages"
